-- Data cleaning
USE BOOKINGS_DB;
GO

-- 1. SILVER.offline_customers_silver
DROP VIEW IF EXISTS SILVER.offline_customers_silver;
GO 

CREATE VIEW SILVER.offline_customers_silver AS 
SELECT DISTINCT 
    CAST(CUSTOMER_UUID AS VARCHAR(90)) AS CUSTOMER_UUID,
    COALESCE(CAST(LOCALE AS VARCHAR(20)), 'unknown') AS LOCALE_CODE,
    UPPER(CAST(STATUS AS VARCHAR(30))) AS STATUS,
    'offline' AS CATEGORY,
    TRY_CAST(TS_CRE AS DATETIME2) AS TS_CRE,
    TRY_CAST(TS_UPD AS DATETIME2) AS TS_UPD
FROM BRONZE.offline_customers
WHERE CUSTOMER_UUID IS NOT NULL 
  AND ONLINE_CUSTOMER_UUID IS NULL;
GO


-- 2. SILVER.online_customers_silver
DROP VIEW IF EXISTS SILVER.online_customers_silver;
GO 

CREATE VIEW SILVER.online_customers_silver AS 
SELECT DISTINCT
    CAST(CUSTOMER_UUID AS VARCHAR(60)) AS CUSTOMER_UUID,
    CAST(LOCALE_CODE AS VARCHAR(20)) AS LOCALE_CODE,
    CAST(STATUS AS VARCHAR(30)) AS STATUS,
    'online' AS CATEGORY, 
    TRY_CAST(TS_CRE AS DATETIME2) AS TS_CRE,
    TRY_CAST(TS_UPD AS DATETIME2) AS TS_UPD
FROM BRONZE.online_customers
WHERE CUSTOMER_UUID IS NOT NULL;
GO


-- 3. SILVER.reservations_silver
DROP VIEW IF EXISTS SILVER.reservations_silver;
GO 

CREATE VIEW SILVER.reservations_silver AS
SELECT DISTINCT
    CAST(CUSTOMER_UUID AS VARCHAR(90)) AS CUSTOMER_UUID,
    TRY_CAST(DT_DAY_BOOKING_DATE AS DATE) AS DT_DAY_BOOKING_DATE,
    TRY_CAST(DT_DAY_MEAL_DATE AS DATE) AS DT_DAY_MEAL_DATE,
    TRY_CAST(AMT_REVENUE_EUR AS FLOAT) AS AMT_REVENUE_EUR,
    TRY_CAST(AMT_REVENUE_USD AS FLOAT) AS AMT_REVENUE_USD,
    TRY_CAST(AMT_REVENUE_LOCAL AS FLOAT) AS AMT_REVENUE_LOCAL,
    TRY_CAST(IS_NET AS BIT) AS IS_NET, 
    CAST(CHANNEL AS VARCHAR(50)) AS CHANNEL,
    CAST(RESERVATION_UUID AS VARCHAR(60)) AS RESERVATION_UUID,
    CAST(RESTAURANT_UUID AS VARCHAR(60)) AS RESTAURANT_UUID,
    CAST(RESTAURANT_CITY AS VARCHAR(100)) AS RESTAURANT_CITY,
    CAST(RESTAURANT_COUNTRY AS VARCHAR(100)) AS RESTAURANT_COUNTRY,
    TRY_CAST(IS_ONLINE AS BIT) AS IS_ONLINE,
    TRY_CAST(PARTY_SIZE AS INT) AS PARTY_SIZE, 
    TRY_CAST(IS_WALK_IN AS BIT) AS IS_WALK_IN,
    CAST(LUNCH_TYPE AS VARCHAR(50)) AS LUNCH_TYPE,
    TRY_CAST(TS_CRE AS DATETIME2) AS TS_CRE,
    TRY_CAST(TS_UPD AS DATETIME2) AS TS_UPD
FROM BRONZE.reservations
WHERE RESERVATION_UUID IS NOT NULL;
GO

select * from SILVER.reservations_silver;

select * from BRONZE.reservations;

select *
from SILVER.reservations_silver
where CUSTOMER_UUID is null;